# result: https://wrench.edu.swampbuds.me/result/0c432031-0e23-43c2-9d77-07f907c300fd
name: assert upper_case_pstr('12345678901234567890123456789012\n3') == ([-858993460], '\n3')
limit: 2000
memory_size: 0x1000
input_streams:
  0x80:
    [
      49,
      50,
      51,
      52,
      53,
      54,
      55,
      56,
      57,
      48,
      49,
      50,
      51,
      52,
      53,
      54,
      55,
      56,
      57,
      48,
      49,
      50,
      51,
      52,
      53,
      54,
      55,
      56,
      57,
      48,
      49,
      50,
      10,
      51,
    ]
  0x84: []
reports:
  - name: Check results
    slice: last
    filter:
      - state
    view: |
      numio[0x80]: {io:0x80:dec}
      numio[0x84]: {io:0x84:dec}
      symio[0x80]: {io:0x80:sym}
      symio[0x84]: {io:0x84:sym}
    assert: |
      numio[0x80]: [10,51] >>> []
      numio[0x84]: [] >>> [-858993460]
      symio[0x80]: "\n3" >>> ""
      symio[0x84]: "" >>> "?"
