limit: 100
memory_size: 256
input_streams:
  0x80: [5, 104, 101, 108, 108, 111]
  0x84: []
reports:
  - name: "Step-by-Step Log"
    slice: all
    view: |
      {pc:hex}: {instruction}
  - name: "Final Output Check"
    slice: last
    view: |
      numio[0x80]: {io:0x80:sym}
      numio[0x84]: {io:0x84:sym}
    assert: |
      numio[0x80]: "" >>> ""
      numio[0x84]: "" >>> "HELLO"
