/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    checkstyle
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

repositories {
    mavenCentral()
}

description = "lab-common"
