package ru.rmntim.common.models;

import java.time.ZonedDateTime;

/**
 * @param id           non-null, positive, unique, autogenerated
 * @param name         non-null, non-empty
 * @param coordinates  non-null
 * @param creationDate non-null, autogenerated
 * @param age          non-null, positive
 * @param color        non-null
 * @param type         non-null
 * @param character    non-null
 * @param head
 */
public record Dragon(Integer id, String name, Coordinates coordinates, ZonedDateTime creationDate, Long age,
                     Color color, DragonType type, DragonCharacter character,
                     DragonHead head) implements Comparable<Dragon> {
    @Override
    public int compareTo(Dragon o) {
        return this.id.compareTo(o.id());
    }
}
