version: "3"

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: "studs"
      POSTGRES_USER: "s409682"
      POSTGRES_PASSWORD: "s409682"
    ports:
      - "5432:5432"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres